language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --no-deps
after_success:
  - travis-cargo --only nightly doc-upload
env:
  global:
    secure: "iENCKNKfyveEXk+OofJDnxGfeVnxHovvLsrtl7eUBev6YGIIlUISZliyCvBrSkZKTeLfdDEP+Q5Mv9tVOMAx/FNiKB9V07WFDahD6xvz+qd3k790gdzgy+0LcNKskBVzDK62zCofvknGVbQa9f5iimhu+wKs9bb+WCxicVWmeRo="



notifications:
  email:
    on_success: never
